language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-backbone-fullstack' ]; then cd .. && eval "mv $currentfolder generator-backbone-fullstack" && cd generator-backbone-fullstack; fi

